using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using RTF;

if (args.Length > 1)
{
    Console.WriteLine("Only accept one arg.");

    return;
}

var currentDirectory = Directory.GetCurrentDirectory();
var path = $"{currentDirectory}/{args[0]}";

var fileExists = File.Exists(path);

if (!fileExists)
{
    Console.WriteLine("File not exists.");

    return;
}

var summary = await File.ReadAllTextAsync(path);

if (string.IsNullOrEmpty(summary))
{
    Console.WriteLine("File content is empty.");

    return;
}

var geminiOptions = new GeminiOptions
{
    ApiKey = Environment.GetEnvironmentVariable("GeminiOptions:ApiKey") ?? string.Empty,
    Url = Environment.GetEnvironmentVariable("GeminiOptions:Url") ?? string.Empty
};

if (string.IsNullOrEmpty(geminiOptions.ApiKey))
{
    Console.WriteLine("API Key not provided.");

    return;
}

if (string.IsNullOrEmpty(geminiOptions.Url))
{
    Console.WriteLine("Url not provided.");

    return;
}

var deckName = string.Empty;

while (string.IsNullOrEmpty(deckName))
{
    Console.WriteLine("What is the deck name to save the flashcards?");

    deckName = Console.ReadLine();
}

var prompt =
    $@"Based on the summary below, generate a JSON object for the ""params"" field used in the AnkiConnect ""addNotes"" action. 
Return only the JSON object with a ""notes"" array, where each note has the following properties:

- ""deckName"": ""{deckName}""
- ""modelName"": always ""Basic""
- ""fields"": an object with ""Front"" (question) and ""Back"" (answer)
- ""options"": with ""allowDuplicate"" set to false
- ""tags"": an array containing only the string ""auto generated by AI""

Return a valid JSON object containing only the ""params"" with the list of notes. Do not include any explanations, comments, or additional text.

Summary to generate flashcards from:
{summary}";


var requestBody = new
{
    contents = new[]
    {
        new
        {
            parts = new[]
            {
                new { text = prompt }
            }
        }
    }
};

var httpClient = new HttpClient();

var geminiResponse = await httpClient.PostAsJsonAsync($"{geminiOptions.Url}{geminiOptions.ApiKey}", requestBody);

if (!geminiResponse.IsSuccessStatusCode)
{
    Console.WriteLine("An error occured when generate flashcards.");

    return;
}

var result = await geminiResponse.Content.ReadFromJsonAsync<GeminiResponse>();

if (result?.Candidates is not { Count: > 0 })
{
    var errorMessage = await geminiResponse.Content.ReadAsStringAsync();

    Console.WriteLine($"An error occured when generate flashcards: {errorMessage}");

    return;
}

var responseContent = result.Candidates[0].Content.Parts[0].Text;

const string ankiUrl = "http://localhost:8765";

var ankiRequestGetDecksName = new AnkiRequestGetDecksName
{
    Action = AnkiActionOptions.DeckNames.ToActionString(),
};

var ankiGetDecksNameContent =
    new StringContent(JsonSerializer.Serialize(ankiRequestGetDecksName), Encoding.UTF8, "application/json");
var ankiGetDecksNamesResponse = await httpClient.PostAsJsonAsync(ankiUrl, ankiGetDecksNameContent);

ankiGetDecksNamesResponse.EnsureSuccessStatusCode();

var decksNamesString = await ankiGetDecksNamesResponse.Content.ReadAsStringAsync();

var decksNameList = JsonSerializer.Deserialize<AnkiResponseGetDecksName>(decksNamesString);


var containsDeck = decksNameList != null && decksNameList.Result.Contains(deckName);

if (!containsDeck)
{
    var createNewDeck = string.Empty;

    while (string.IsNullOrEmpty(createNewDeck))
    {
        Console.WriteLine("Deck not exist, want to create a new deck (y/n)?");

        createNewDeck = Console.ReadLine();
    }

    if (createNewDeck.Equals("n", StringComparison.OrdinalIgnoreCase))
    {
        Console.WriteLine("Want to rename the deck (y/n)?");

        var renameDeck = Console.ReadLine();

        if (string.IsNullOrEmpty(renameDeck) || renameDeck.Equals("n", StringComparison.OrdinalIgnoreCase))
            return;

        if (renameDeck.Equals("s", StringComparison.OrdinalIgnoreCase))
        {
            Console.WriteLine("New deck name:");

            var newDeckName = string.Empty;

            while (string.IsNullOrEmpty(newDeckName))
            {
                Console.WriteLine("Deck name can't be blank. Type a valid deck name:");

                newDeckName = Console.ReadLine();
            }

            deckName = newDeckName;
        }
    }
}

var ankiRequestAddNote = new AnkiRequestAddNote
{
    Action = AnkiActionOptions.AddNote.ToActionString(),
    Params = new { responseContent }
};

var ankiAddNoteContent =
    new StringContent(JsonSerializer.Serialize(ankiRequestAddNote), Encoding.UTF8, "application/json");
var ankiAddNoteResponse = await httpClient.PostAsJsonAsync(ankiUrl, ankiAddNoteContent);

ankiAddNoteResponse.EnsureSuccessStatusCode();